import "./globals.css";

export const metadata = {
  title: "Folder Explorer",
  description: "Generated by Next.js + Bun",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
